### ISSUE TITLE
Can you please post some examples

### ISSUE THREAD

**Issue by Raj123456788** [yanrk/boost_web#1]
Trying to send a chunked buffer from a file to the server. Example is appreciated. trying to acheive below javascript code in C++
Debugger listening on ws://127.0.0.1:47500/5c13a73f-7e90-4ee2-b2b4-72144142590c(when I set the server_node.host=127.0.0.1 is it ws:// or wss://) how can I set it?

Javascript:
const server = https.createServer({
        key: fs.readFileSync('server.key'),
        cert: fs.readFileSync('server.crt')
    });
    const img = fs.readFileSync('./background.jpg');
    server.on('request', async (req, res) => {
        var request = url.parse(req.url, true);
        var action = request.pathname;

        if (action === '/mask') {
            var chunks = [];
            req.on('data', (chunk) => {
                chunks.push(chunk);
            });
            req.on('end', async () => {
                const image = tf.node.decodeImage(Buffer.concat(chunks));
                segmentation = await net.segmentPerson(image, {
                    flipHorizontal: false,
                    internalResolution: 'medium',
                    segmentationThreshold: 0.7,
                });
                res.writeHead(200, { 'Content-Type': 'application/octet-stream' });
                res.write(Buffer.from(segmentation.data));
                res.end();
                tf.dispose(image);
            });

**Comment by Raj123456788** [comment]
How would you send back as response
res.writeHead(200, {'Content-Type': 'image/jpeg' });
res.end(img, 'binary');



 if(request_target=="/background")
    {
        boost::beast::http::response<boost::beast::http::string_body> res{ };
        res.set(boost::beast::http::field::content_type, "image/jpeg; binary");
        res.content_length(200);

        std::ifstream file("background.jpg", std::ios::binary | std::ios::ate);
        std::streamsize size = file.tellg();
        file.seekg(0, std::ios::beg);

        std::vector<char> buffer(size);
        if (file.read(buffer.data(), size))
        {
            /* worked! */
        }
        
          std::cout << "Background" <<  std::endl;

        res.body()=buffer.data();
        return (send(std::move(res))); // why this is not sending the response?
    }

**Comment by Raj123456788** [comment]
@yanrk : Can you please answer?

**Comment by yanrk** [comment]
It not support 'chunk' yet, but send a file as stream should be ok.

**Comment by yanrk** [comment]
If you are using HTTP-related functionality, you need to implement two virtual functions:

```c++
virtual bool target_is_path(const std::string & target) override;
virtual bool handle_request(const BoostWeb::HttpConnectionBase & connection, const BoostWeb::HttpRequestBase & request, BoostWeb::HttpResponseBase & response) override;
```

This function '*target_is_path()*' defines whether the '*target*' is a path or not: if it is a path and it is exist, it is automatically sent without notification; and if it is not, will call '*handle_request()*'

**Comment by yanrk** [comment]
```c++
bool TestService::init()
{
    ...
    BoostWeb::ServiceNode service_node;
    service_node.root = "f:/codes/web/html/";
    ...
    return (m_web_manager.init(this, &service_node, 1, true, crt_file, key_file, 1));
}
```

'*service_node.root*' specifies the actual root path

in the example '*http://localhost:12345/api/something*' specify all business requests, _target_is_path()_ can be:

```c++
bool TestService::target_is_path(const std::string & target)
{
    return ("/api/" != target.substr(0, 5));
}
```

and file '*f:/codes/web/html/index.html*' can be accessed through this URL: '*http://localhost:12345/index.html*'

**Comment by yanrk** [comment]
It not support download either

**Comment by Raj123456788** [comment]
Thanks for the comments above. 
I am stuck where response needs to be a buffer from a file.am I missing something below:
      if (action === '/background') {
            res.writeHead(200, {'Content-Type': 'image/jpeg' });
            res.end(img, 'binary');
        }
to more understand: https://stackoverflow.com/questions/14243100/response-writehead-and-response-end-in-nodejs
C++:
   void handle_request(WebServiceBase * service, const std::string & doc_root, const HttpConnectionBase & connection, boost::beast::http::request<Body, Fields> && req, Send && send)
{
auto const background = [&req](boost::beast::string_view target)
  {
      boost::beast::http::response<boost::beast::http::string_body> res{ };
              res.set(boost::beast::http::field::content_type, "image/jpeg; binary");
              res.content_length(200);

              std::ifstream file("/Users/background.jpg", std::ios::binary | std::ios::ate);
              std::streamsize size = file.tellg();
              file.seekg(0, std::ios::beg);

              std::vector<char> buffer(size);
              if (file.read(buffer.data(), size))
              {
                  res.body()=buffer.data(); /// this is not working. Any other suggestions?
                  res.prepare_payload();
                  
              }
              
                std::cout << "Background" <<  std::endl;
      
              return(res);
  };
}

**Comment by yanrk** [comment]
Maybe you can reference ‘*boost_web/inc/http_utility.h*’ and  ‘*boost_web/inc/http_utility.cpp'*

It show how to send a file, seems like

```c++
boost::beast::error_code ec;
boost::beast::http::file_body::value_type body;
body.open(path.c_str(), boost::beast::file_mode::scan, ec);

const uint64_t body_size = body.size();

boost::beast::http::response<boost::beast::http::file_body> res{ std::piecewise_construct, std::make_tuple(std::move(body)), std::make_tuple(boost::beast::http::status::ok, req.version()) };
res.set(boost::beast::http::field::server, "boost web server 1.0 by yanrk");
res.set(boost::beast::http::field::content_type, get_mime_type(path));
res.set(boost::beast::http::field::access_control_allow_origin, "*");
res.content_length(body_size);
res.keep_alive(req.keep_alive());
send(std::move(res));
```

**Comment by Raj123456788** [comment]
one last question: What if I have a buffer.dataptr instead of the path? Also, is there something I can set(variable) in testService.cpp that I can retrieve in http_utility.h?

**Comment by yanrk** [comment]
you can send with buffer like this 

```
std::ifstream file(path.c_str(), std::ios::binary);
std::streamsize size = file.tellg();
file.seekg(0, std::ios::beg);

std::vector<char> data(size);
file.read(data.data(), size);

http::response<http::buffer_body> res{ http::status::ok, req.version() };
res.set(http::field::server, BOOST_BEAST_VERSION_STRING);
res.set(http::field::content_type, mime_type(path));
res.content_length(size);
res.keep_alive(req.keep_alive());
res.body().data = data.data();
res.body().size = data.size();
res.prepare_payload();
send(std::move(res));
```


reference by *https://github.com/boostorg/beast/issues/1637*

**Comment by Raj123456788** [comment]
Error: message	const char *	"need buffer"	0x0000700008f2fd59 . data.data() & data.size() is empty. What are we missing?

How can I send the path of the file from testservice.cpp  ?

I added below code testservice.cpp:
void handle_request(WebServiceBase * service, const std::string & doc_root, const BoostWeb::HttpConnectionBase & connection, boost::beast::http::request<Body, Fields> && req, Send && send)

But it still hits http_utility.h 
 void handle_request(WebServiceBase * service, const std::string & doc_root, const BoostWeb::HttpConnectionBase & connection, boost::beast::http::request<Body, Fields> && req, Send && send)

how can I make sure it hits the testservice.cpp and not the http_utility.cpp.

**Comment by yanrk** [comment]
change '*target_is_path()*', let it return false, then, '*handle_request()*' will be called, but **Body** is '*boost::beast::http::**string_body***' in *http_utility.h*

```
HttpResponse<boost::beast::http::string_body, Fields> response(res);
service->handle_request(connection, request, response);
```

and *response* can not access *Body* on *test_service.cpp*， you need change the codes

**Comment by yanrk** [comment]
if you just want to test ***buffer_body***, you can test it with the URL code: https://www.boost.org/doc/libs/1_72_0/libs/beast/example/http/server/sync/http_server_sync.cpp

**Comment by Raj123456788** [comment]
change 'target_is_path()', let it return false: I am getting this error: Void function 'handle_request' should not return a value. 

I just need to send the buffer dataptr as response that will change every sec. Is there a variable that I can set in test_service.cpp that I can access in http_utility.h? Any idea?

**Comment by yanrk** [comment]
what I mean change '*target_is_path()*'

```c++
bool TestService::target_is_path(const std::string & target)
{
    return (false); // return ("/api/" != target.substr(0, 5));
}
```

**Comment by Raj123456788** [comment]
I tried adding below code  
bool TestService::target_is_path(const std::string & target)
{
    return (false); // return ("/api/" != target.substr(0, 5));
}
I called this from main.cpp as well

it is still hitting the same the http_utility.h. Can you please run and let me know.



For this example: if you just want to test buffer_body, you can test it with the URL code: https://www.boost.org/doc/libs/1_72_0/libs/beast/example/http/server/sync/http_server_sync.cpp
How can I add the cert and key?
what to add for auto const doc_root?

**Comment by Raj123456788** [comment]
<img width="1073" alt="Screen Shot 2020-09-29 at 7 09 46 PM" src="https://user-images.githubusercontent.com/16295521/94635391-68fa3280-0287-11eb-9690-ab7e8d3b880c.png">
Please read my above comments. Please tell me if I need to remove the .cpp files in order for it to hit Testservice.cpp


void TestService::handle_request(WebServiceBase * service, const std::string & doc_root, const BoostWeb::HttpConnectionBase & connection,boost::beast::http::request<Body, Fields>  && req, Send && send)

**Comment by yanrk** [comment]
the template function ***handle_request()*** on ***http_utility.h*** show how to handle a http request

```
template <class Body, class Fields, class Send>
void handle_request(WebServiceBase * service, const std::string & doc_root, const HttpConnectionBase & connection, boost::beast::http::request<Body, Fields> && req, Send && send)
{
    ...
    const std::string request_target(req.target());
    ...
    if (service->target_is_path(request_target)) // it is a file
    {
        ...
        boost::beast::http::response<boost::beast::http::file_body> res{ ... };
        ...
        return (send(std::move(res))); // send file
    }
    else // it is not a file
    {
        ...
        boost::beast::http::response<boost::beast::http::string_body, Fields> res;
        ...
        HttpRequest<Body, Fields> request(req);
        HttpResponse<boost::beast::http::string_body, Fields> response(res); // string_body here, but you can change to buffer_body
        ...
        service->handle_request(connection, request, response); // you need fill the response
        ...
        return (send(std::move(res))); // send response
    }
}
```

This function ***target_is_path()*** determines whether the target should handle as a file by the library, or the response should populate by the consumer

**all http(s) requests come in from this template function, and you can step through it and even modify the code**

in boost_web, doc_root is the root directory of all files that can be accessed, usually they are CSS/JS/HTML files

about the certificate, you can look at the boost_web, or start with:
https://www.boost.org/doc/libs/1_72_0/libs/beast/example/http/server/sync-ssl/http_server_sync_ssl.cpp

all boost.beast server code on URL:
https://www.boost.org/doc/libs/1_72_0/libs/beast/doc/html/beast/examples.html#beast.examples.servers

**Comment by yanrk** [comment]
about the certificate, you also have to build boost with openssl

**Comment by Raj123456788** [comment]
Thank you for the explanation.  Pretty to close to get it working now. It hits TestService.cpp now :)

How can I do send 
 boost::beast::error_code ec;
        boost::beast::http::file_body::value_type body;
     body.open("/Users/Downloads/neural-greenscreen-master/background2.jpg", boost::beast::file_mode::scan, ec);
 const uint64_t body_size = body.size();
 boost::beast::http::response<boost::beast::http::file_body> res{ std::piecewise_construct, std::make_tuple(std::move(body)), std::make_tuple(boost::beast::http::status::ok, req.version()) };
    res.set(boost::beast::http::field::content_type, "image/jpeg; binary");
    res.content_length(body_size);
        res.keep_alive(req.keep_alive());
        send(std::move(res));

You said service->handle_request(connection, request, response); // you need fill the response. But my response is in Testservice.cpp above 
How can I send it from Testservice.cpp
bool TestService::handle_request(const BoostWeb::HttpConnectionBase & connection, const BoostWeb::HttpRequestBase & request, BoostWeb::HttpResponseBase & response)
{
}

**Comment by yanrk** [comment]
if you just want to send file, change "target_is_path()" will get you want
if you want to send file by yourself, change the template function handle_request() of http_utility.h (string_body change buffer_body or file_body, and so on, you can change everything to get your wish)

**Comment by yanrk** [comment]
you have to debug the template function handle_request() to know what did it do, when you understand the logic of this function, you can easily figure out how to do it, actually, I am losing sight of your true purpose.

**Comment by yanrk** [comment]
in the sample ***d:/test_web_service/*** is doc_root, URI start with ***/api/*** means business request will call TestService::handle_request()

```
bool TestService::init()
{
    ...
    BoostWeb::ServiceNode service_node;
    service_node.host = "0.0.0.0";
    service_node.port = 12345;
    service_node.root = "d:/test_web_service/"; // doc_root, all files in here
    ...
    service_node.protocol = BoostWeb::support_protocol_t::protocol_http;
    return (m_web_manager.init(this, &service_node, 1, false, nullptr, nullptr, 1));
}

bool TestService::target_is_path(const std::string & target)
{
    return ("/api/" != target.substr(0, 5)); // only '/api/xxx' is business request, the others are files
}
```

then when you can access *d:/test_web_service/pic/abc.jpg* with URL http://127.0.0.1:12345/pic/abc.jpg

access *d:/test_web_service/hello.html* with URL http://127.0.0.1:12345/hello.html

http://127.0.0.1:12345 is default to access *d:/test_web_service/index.html*

http://127.0.0.1:12345/test?abc is default to access *d:/test_web_service/test?abc*

http://127.0.0.1:12345/api/login?username=xx&password=11 will call TestService::handle_request() as a business request

**Comment by Raj123456788** [comment]
My apologies, if you are loosing the sight. Currently the response.set_body in handle_request only accepts the string but what if some one needs to send something else like buffer or something not string. I will try your above suggestions. Thanks!

**Comment by Raj123456788** [comment]
Sorry to bother again: I need to send buffer from testservice.cpp . Please let me know if I have missed anything Handle_request() to http_utility.h
I added below http_utility.h

1. boost::beast::http::response<boost::beast::http::buffer_body> res2; // should I keep this as string_body? 
2. res2.set(boost::beast::http::field::server, "boost web server 1.0 by yanrk");
3. res2.set(boost::beast::http::field::content_type, "text/html");
4. res2.set(boost::beast::http::field::access_control_allow_origin, "*");
5. HttpRequest<Body, Fields> request(req);
6. HttpResponse<boost::beast::http::buffer_body, Fields> response(res2); // this throws error if I keep it as string_body in 1. above "No matching constructor for initialization of 'HttpResponse<boost::beast::http::buffer_body, boost::"

service->handle_request(connection, request, response);


What I want to do "Buffer is already available from external source to Testservice."

Now whatI need help with:
1) How should set up the  request,response for  service->handle_request(connection, request,response); in http_utility.h

2) Push the buffer as response to handle_request in Testservice.cpp
example: response.set_body(buffer);

3)http_utility.h receives this buffer and sends as response.
example:
res.content_length(size);
res.keep_alive(req.keep_alive());
res.body().data = response.data();
res.body().size = response.size();
res.prepare_payload();
send(std::move(res));


Will be waiting for your response. Thanks!



<img width="1361" alt="Screen Shot 2020-09-30 at 11 38 03 AM" src="https://user-images.githubusercontent.com/16295521/94725970-6e03c400-0311-11eb-96ef-a4b60d98f6d5.png">

**Comment by Raj123456788** [comment]
Hey @yanrk : I hope you are doing good. Here is what I am stuck with.
boost::beast::http::response<boost::beast::http::string_body, Fields> res;
HttpRequest<Body, Fields> request(req);
HttpResponse<boost::beast::http::string_body, Fields> response(res);
service->handle_request(connection, request, response);
**// I receive the string buffer from handle_request. since response can only send a string?**
auto f= response.get_body();
std::make_tuple(boost::beast::http::status::ok, req.version()) };
boost::beast::http::response<boost::beast::http::buffer_body> res1{ boost::beast::http::status::ok, req.version() };// **does it have the right parameters?**
char char_array[200];
strcpy(char_array, f.c_str()); // convert string to char buffer
res1.body().data= char_array; // **Is this the right way of adding buffer to response body?** Can we do it some other way?
res1.body().size=200;
res1.set(boost::beast::http::field::content_type, "image/jpeg; binary");
res1.keep_alive(req.keep_alive());
return (send(std::move(res1)));

// Nothing happens: It says  need_buffer. I would say same as: https://github.com/boostorg/beast/issues/2088

**Comment by yanrk** [comment]
the current implements of set_body()/get_body() is for string_body, you can change them for buffer_body

**Comment by yanrk** [comment]
I found something wrong in your code

```c++
std::ifstream file("background.jpg", std::ios::binary | std::ios::ate);
file.seekg(0, std::ios::end); // you miss this line
std::streamsize size = file.tellg();
file.seekg(0, std::ios::beg);
```

and I'm sorry that I don't know that much about buffer_body either, but if it's just to send a binary file, I've decided that string_body is okay too

```c++
bool TestService::handle_request(const BoostWeb::HttpConnectionBase & connection, const BoostWeb::HttpRequestBase & request, BoostWeb::HttpResponseBase & response)
{
    const char * path = "D:\\test\\main.cpp";
    std::ifstream file(path, std::ios::binary);
    file.seekg(0, std::ios::end);
    std::streamsize size = file.tellg();
    file.seekg(0, std::ios::beg);
    
    std::string data(size, 0x0);
    file.read(&data[0], size);
    
    response.set_body(std::move(data));
    return (true);
}
```

**Comment by Raj123456788** [comment]
> the current implements of set_body()/get_body() is for string_body, you can change them for buffer_body

Changing the current implements of set_body()/get_body() is for string_body, you can change them for buffer_body I get these errors. I have already tried that.
Screen Shot 2020-09-30 at 11.38.03 AM

**Comment by Raj123456788** [comment]
@yanrk Thanks for the Handle_request code: One last thing
Can you please help me with this on the http_utility.h side:

```
  boost::beast::http::response<boost::beast::http::buffer_body> res1{ boost::beast::http::status::ok, req.version() };
    HttpRequest<Body, Fields> request(req);
     HttpResponse<boost::beast::http::buffer_body, Fields> response(res1);
 service->handle_request(connection, request, response);
auto f= response.get_body();
std::make_tuple(boost::beast::http::status::ok, req.version()) };
 boost::beast::http::response<boost::beast::http::buffer_body> res1{ boost::beast::http::status::ok, req.version() };
  // declaring character array
char char_array[200];
            
              // copying the contents of the
              // string to char array
            strcpy(char_array, f.c_str());
            res1.body().data= char_array;
            //res1.body().data= response.get_body(); // I can do this if based on if the response is string buffer?
            res1.body().size=1200;
            res1.set(boost::beast::http::field::content_type, "image/jpeg; binary");
            res1.keep_alive(req.keep_alive());
            return (send(std::move(res1)));
```
Getting these errors for above code
<img width="1361" alt="Screen Shot 2020-09-30 at 11 38 03 AM" src="https://user-images.githubusercontent.com/16295521/94954026-522d2900-049d-11eb-8c54-607e5f7020d7.png">


Or We can keep it as string Body: But even below code is not working

boost::beast::http::response<boost::beast::http::string_body, Fields> res;
HttpRequest<Body, Fields> request(req);
HttpResponse<boost::beast::http::string_body, Fields> response(res);
service->handle_request(connection, request, response);
// I receive the string buffer from handle_request. since response can only send a string?
auto f= response.get_body();
std::make_tuple(boost::beast::http::status::ok, req.version()) };
boost::beast::http::response<boost::beast::http::buffer_body> res1{ boost::beast::http::status::ok, req.version() };
char char_array[200];
strcpy(char_array, f.c_str());
res1.body().data= char_array;
res1.body().size=200;
res1.set(boost::beast::http::field::content_type, "image/jpeg; binary");
res1.keep_alive(req.keep_alive());
return (send(std::move(res1)));

**Comment by Raj123456788** [comment]
Still no luck. If you find anything let me know. If you can suggest some other libraries please let me know Thanks @yanrk

**Comment by Raj123456788** [comment]
If f is the response from the handle_request.  This is the way you assign it.                             
res.body() = f;
                            res.prepare_payload();
                            res.keep_alive(req.keep_alive());
                            return (send(std::move(res)));
